# Using Jupyter notebooks

A Jupyter notebook is made of cells, which can contain code or text (aka markdown).

<p>Press <i>a</i> to add a cell above or <i>b</i> to add a cell below your current position. Press <i>y</i> to a change the cell type to "code" or press <i>m</i> to change the cell type to "markdown". In a markdown cell, you can type html code so that you can format your text as explained in the following <i>unordered list</i>:
<ul>
<li>You can write something <b>bold</b></li>
<li>You can write something in <i>italic</i></li>
</ul></p>
<p>You could also use <i>ordered lists</i>, like this one:
<ol>
<li>This is the first item in the ordered list</li>
<li>This is the second item in the ordered list</li>
</ol></p>

You can "execute" cells by pressing CTRL+ENTER or SHIFT+ENTER. Executing a code cell will run the code; executing a markdown cell will vidualize the text according to the markdown language used. For example, the text above is generated by typing the following in a markdown cell, and then pressing SHIFT+ENTER.

<p>Press <i>a</i> to add a cell above or <i>b</i> to add a cell below your current position. Press <i>y</i> to a change the cell type to "code" or press <i>m</i> to change the cell type to "markdown". In a markdown cell, you can type html code so that you can format your text as explained in the following <i>unordered list</i>:
<ul>
<li>You can write something <b>bold</b></li>
<li>You can write something in <i>italic</i></li>
</ul></p>
<p>You could also use <i>ordered lists</i>, like this one:
<ol>
<li>This is the first item in the ordered list</li>
<li>This is the second item in the ordered list</li>
</ol></p>

You can delete cells by pressing DD, or copy-paste them or move-paste them with C or X, followed by V

# Python Review

The following cell makes sure that all of the outputs of a cell are printed. We will start all of our notebooks with this code.

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Basics

### Variables are dynamically typed

We don't need to specify variable types -- the interpreter assigns it automatically. A variable <b>a</b> can change type.  The following example shows a variable <i>a</i> which is initialized to an integer (int) and then assigned to a string (str).

In [1]:
a = 3

In [2]:
type(a)

int

In [3]:
a = 'Hello'

In [4]:
type(a)

str

### Mathematical operations

Here are examples of addition (+), subtraction (-), multiplication (\*), division, (/) and exponentiation (\*\*)

In [7]:
a = 2
b = 3
a + b
a - b
a * b
a / b
a ** b

5

-1

6

0

8

Note that as in other programming languages, division between integers results in the <i>floored</i> integer result.  This problem is fixed by using floats instead.

In [6]:
a = 2.0
b = 3
a / b

0.6666666666666666

To print a sentence with numerical results, we need to convert the number to strings using the function <i>str</i>

In [7]:
print ('The value of a is ' + str(a))

The value of a is 2.0

### Conditions

In the following example, we will check whether a (which is 3) is greater than b (which is 5)

In [8]:
a = 3
b = 5
if a < b:
    print ('a is smaller than b')
    print ('another sentence')
else:
    print ('a is greater than or equal to b')

a is smaller than b
another sentence

Note that the indentation in the code above is <b>needed</b> to indicate the blocks of code to execute if the condition is true or false.

A more concise "IF STATEMENT":

In [9]:
val = 1 if a > b else 0

In [10]:
val

0

### Functions

In Python, 
<ul>
<li>functions do not have a return type</li>
<li>The parameters do not have a type</li>
<li>Parameters may have a default value</li>
<li>Indentation (not braces) define the scope of the function</li>
</ul>

Here is a function that writes a message and then sums two numbers <i>a</i> and <i>b</i>. The default value of <i>b</i> is 0.

In [11]:
def mysum (a,b=0):
    print ('mysum is starting')
    return a+b

Call mysum with a=4 and b=5

In [12]:
mysum(4,5)

mysum is starting

9

Call mysum with a=6 and b=0

In [13]:
mysum(6)

mysum is starting

6

<b>In class exercise</b>: write a function that performs <i> a / b </i> and that always returns the correct (i.e., float) result even if the inputs are integer. For example: mydiv(1,2) should return 0.5, and not 0.

In [14]:
def mydiv(a,b):
    return (a+0.0) / b

In [15]:
mydiv(1,2)

0.5

## Lists

Lists are ordered and mutable sequences of items (of possibly different types). Denoted by square brackets.

Here is a list with 5 elements, including integers, floats, and lists

In [16]:
a = [3, -4.5, 'hello', [-1, 1], -1, 2]

Indexing starts at 0 (first item). It can be negative too.

In [17]:
a[0]

3

In [21]:
a[3]

[-1, 1]

You can use negative indices to start counting from the end. For example, here is how you get the second to last element.

In [18]:
a[-2]

-1

The function <i>len</i> returns the length of the list

In [19]:
len(a)

6

The built-in <i>range</i> function builds lists of integers.

For example, this is how to create a list from 0 to 9

In [20]:
range(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Here is a list from 3 to 9

In [21]:
range(3,10)

[3, 4, 5, 6, 7, 8, 9]

And here is a list from 3 to 9 in steps of 4

In [22]:
range(3,10,4)

[3, 7]

Important methods of List are:
<ul>
<li><b>append</b>: add an item at the end</li>
<li><b>insert</b>: insert an item at a specific point</li>
<li><b>pop</b>: remove and return the item at a specific index</li>
</ul>

In [23]:
l = [3,7]

In [24]:
l.append(6.0 / 7.0)

In [25]:
l

[3, 7, 0.8571428571428571]

In [26]:
l.insert(2,-10)
l

[3, 7, -10, 0.8571428571428571]

In [27]:
l.pop()

0.8571428571428571

In [28]:
l

[3, 7, -10]

### Slicing

We can select part of a list with the : operator. a[1:4] returns a list containing the items from index 1 (included) to index 4 (excluded). a[:3] returns a list containing all elements up to index 3 (excluded)

In [37]:
a

[3, -4.5, 'hello', [-1, 1], -1, 2]

In [38]:
a[1:4]

[-4.5, 'hello', [-1, 1]]

In [39]:
a[-4:-1]

['hello', [-1, 1], -1]

In [40]:
a[:3]

[3, -4.5, 'hello']

In [41]:
a[3:]

[[-1, 1], -1, 2]

In [42]:
a[:]

[3, -4.5, 'hello', [-1, 1], -1, 2]

In [43]:
a

[3, -4.5, 'hello', [-1, 1], -1, 2]

Slices provide a <b>view</b>, not a copy, of the list. That is, modifications on a slice apply to the list.

In [45]:
a

[3, -4.5, 'hello', [-1, 1], -1, 2]

In [46]:
a[:2]

[3, -4.5]

In [47]:
a[:2] = [0, 0]

In [48]:
a

[0, 0, 'hello', [-1, 1], -1, 2]

### Concatenate lists

In [50]:
a = [1,2,3]
b = [10, 11, 12]
a + b

[1, 2, 3, 10, 11, 12]

In [52]:
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [53]:
a * 3 + b

[1, 2, 3, 1, 2, 3, 1, 2, 3, 10, 11, 12]

### Check presence

We can check whether a list contains an item

In [7]:
a

[3, -4.5, 'hello', [-1, 1], -1, 2]

In [8]:
2 in a

True

In [10]:
'iua' in a

False

## Tuples

Just like lists, but immutable. Denoted by ().

In [59]:
a = [1, 2, 3, -10, 'tttt', -10]
a

[1, 2, 3, -10, 'tttt', -10]

In [60]:
t = (1, 2, 3, -10, 'tttt', -10)
t

(1, 2, 3, -10, 'tttt', -10)

In [65]:
%timeit t[2:4]

10000000 loops, best of 3: 52.9 ns per loop

In [66]:
%timeit a[2:4]

10000000 loops, best of 3: 96.9 ns per loop

## Dictionaries

Dictionaries are data structures that contain (key, value) pairs, where they keys are unique. They are denoted by curly brackets.

<b>Example</b>: Let us make a dictionary where the keys are letters and the values are booleans indicating which letters are vowels.

In [68]:
vowels = {'a': True, 'b': False, 'c': False, 'd':False, 'e': True}
vowels

{'a': True, 'b': False, 'c': False, 'd': False, 'e': True}

Values are accessed using the keys.

In [69]:
vowels['b']

False

In [70]:
vowels['e']

True

In [71]:
vowels[45]

KeyError: 45

You can use the method <b>has_key</b> to check whether it contains a key

In [72]:
vowels.has_key(45)

False

<b>In-class exercise</b>: make a dictionary that reports the number of students in each course. Assume that there are three courses (data science, linux, and statistics) with 28, 23, and 28 students, respectively.

In [73]:
d = {'data science': 28, 'linux': 23, 'statistics': 28}
d

{'data science': 28, 'linux': 23, 'statistics': 28}

Equivalently, we can add elements one by one:

In [75]:
d1 = {}
d1['data science'] = 28
d1['linux'] = 23
d1['statistics'] = 28
d1

{'data science': 28, 'linux': 23, 'statistics': 28}

Testing equality:
<ul>
<li><b>==</b> tests component-wise equality</li>
<li><b>is</b> tests whether the instance is the same</li>
</ul>

In [76]:
d == d1

True

In [77]:
d is d1

False

## <i>For...in</i> loops

The for loops in Python are more like "foreach" loops

In [78]:
for i in [1, 'hello', 9.98]:
    print ('The current value is ' + str(i))

The current value is 1
The current value is hello
The current value is 9.98

A very typical loop:

In [79]:
for i in range(10):
    print("i^2 = " + str(i**2))

i^2 = 0
i^2 = 1
i^2 = 4
i^2 = 9
i^2 = 16
i^2 = 25
i^2 = 36
i^2 = 49
i^2 = 64
i^2 = 81

### List comprehension

We can create lists (or tuples, or dictionaries) through loops using a very dense syntax called "List comprehension"

<b>Example</b>: create a list with these values: 0, 1, 4, 9, 16, ..., 81

In [80]:
# without list comprehension
l = []
for i in range(10):
    l.append(i ** 2)
l

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [82]:
l = [i ** 2 for i in range(10)]
l

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Build the same list but we want 0s in the first 3 elements

In [90]:
l = [i ** 2 if i >= 3 else 0 for i in range(10)]
l

[0, 0, 0, 9, 16, 25, 36, 49, 64, 81]

Creating a Dictionary {0:0, 1:1, 2:4, 3:9, 4:16, ..., 9:81}

In [11]:
{i: i**2 for i in range(10)}

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

### Looping through dictionary entries

We can loop through dictionary keys

In [105]:
for k in d.keys():
    print ('key: ' + k)

key: data science
key: statistics
key: linux

We can loop through dictionary values:

In [106]:
for v in d.values():
    print ('value: ' + str(v))

value: 28
value: 28
value: 23

We can loop through dictionary (key,value) pairs

In [107]:
for k,v in d.items():
    print ('key ' + k + ' is associated to value ' + str(v))

key data science is associated to value 28
key statistics is associated to value 28
key linux is associated to value 23

## Strings

Strings are another type of sequence, and they can be sliced and accessed just like any sequence.

In [91]:
s = 'Welcome to the best Data Science course ever!'

In [92]:
len(s)

45

Some important string methods:
<ul>
<li><b>replace</b>: replaces the occurrences of a string with another</li>
<li><b>lower/upper</b>: makes the string lower/upper case</li>
<li><b>rstrip/lstrip</b>: remove the occurrences of certain trailing characters on the right or left</li>
<li><b>split</b>: splits the string in substrings</li>
</ul>

In [93]:
s.replace('best', 'worst')

'Welcome to the worst Data Science course ever!'

In [94]:
s.lower()

'welcome to the best data science course ever!'

In [96]:
s.rstrip('!?.:; ')

'Welcome to the best Data Science course ever'

In [97]:
s.split()

['Welcome', 'to', 'the', 'best', 'Data', 'Science', 'course', 'ever!']

<b>In class exercise:</b> In one line of code, create a list containing all words in the string s after making them lower case and eliminating the punctuation (?,.:;!) at the end. <i>Hint</i>: use list comprehension.

In [ ]:
# do it on your own

## Files I/O

Files can be opened in these modes:
<ul>
<li><b>w</b>: write (overwrite the file; create the file if it does not exist)
<li><b>a</b>: append (do not overwrite the file)
<li><b>r</b>: read
</ul>

Let us now create a file with two lines

In [98]:
f = open('myfile.txt', 'w')

In [99]:
f.write('This is line #1\n') # \n means new line
f.write('This is the second line\n')

Files must be closed, or else they may stay locked.

In [100]:
f.close()

Let us now read from that file

In [101]:
f = open('myfile.txt', 'r')

In [102]:
for line in f:
    print line

This is line #1

This is the second line

In [103]:
f.close()